[ipa_clients]
# Hosts a desenrolar — agregar todos los que necesites
app-jboss-01.local      ansible_user=root
# app-jboss-02.local    ansible_user=root
# web-server-01.local   ansible_user=root

[ipa_servers]
idm01.idm.daytwo.cloud  ansible_user=root

